---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
      # Make sure to add the otlp receiver.
      # This will open up the receiver on port 4317
      otlp:
        protocols:
          grpc:
            endpoint: "opentelemetrycollector.poc.svc.cluster.local:4317"
          http:
            endpoint: "0.0.0.0:4318"  
    processors:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
data:
  agent.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
    processors:
    exporters:
      jaeger:
        endpoint: jaeger-collector.poc.svc.cluster.local:14250
        tls:
          insecure: true
      prometheusremotewrite:
        endpoint: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
        external_labels:
          cluster: prod
      logging:
    service:
          pipelines:
            traces:
              receivers: [otlp]
              processors: []
              exporters: [jaeger]
            metrics:
              receivers: [otlp]
              processors: []
              exporters: [prometheusremotewrite, logging]